services:
  chatserver:
    container_name: chatserver
    build: .
    ports:
      - '443:443'
      - '3001:3001'
    volumes:
      - ./chat_new_7.db:/app/chat_new_7.db
      - /etc/letsencrypt/live/apitoraspi.ddns.net:/app/letsencrypt:ro 
      - ./public:/app/public
    env_file:
      - .env
    restart: unless-stopped

