name: 🚀 Deploy to Raspberry Pi

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repo
        uses: actions/checkout@v3

      - name: 📡 Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            cd /home/nadine/website-server
            git pull --rebase origin main
            docker compose up -d --build
            curl -s \
              --form-string "token=${{ secrets.APITOKEN }}" \
              --form-string "user=${{ secrets.USERKEY }}" \
              --form-string "message=✅ Deployment auf dem Raspberry Pi abgeschlossen" \
              https://api.pushover.net:443/1/messages.json
          timeout: 3600s
          command_timeout: 2400s
